### ISSUE TITLE
TX Pin only on Reader? Special wiring on Arduino needed?

### ISSUE THREAD

**Issue by ozett** [SensorsIot/Animal-RFID-Reader#1]
Hi,
as always all very interesting videos and i bought a animal-rfid reader and found only TX pin for sending on it.

Is there a special wiring needed on arduino-side?
does the code for serial need special setup with the missing RX?
does one need the mega with explicit serial-hw-pins?

or do i neet a RX-lib only? ->https://forum.arduino.cc/index.php?topic=112013.15

i may try your code as it is on an nano and see if it magically works...

**Comment by lamachine** [comment]
Bump.   Also came here looking for a wiring diagram.  I actually bought two of the long range meters on your suggestion.  Great stuff!

**Comment by lamachine** [comment]
Grr, just searched your web page and found affiliate links.  I will use them next time!

**Comment by SensorsIot** [comment]
You should be able to use software serial and you only need RX on the MCU
